import Link from "next/link";
import "./globals.css";
import Image from "next/image";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-screen h-screen">
      
        {children}

      </body>
    </html>
  );
}
